#!/bin/sh

GPIO=16

if [ ! -e /sys/class/gpio/gpio${GPIO} ];then
	echo $GPIO >/sys/class/gpio/export
fi

if [ "`cat /sys/class/gpio/gpio${GPIO}/direction`" != "out" ];then
	echo out >/sys/class/gpio/gpio${GPIO}/direction
fi

feed_dog()
{
        local count=5
        for i in $(seq 1 $count);
        do
                echo 1 >/sys/class/gpio/gpio${GPIO}/value
                sleep 0.01
                echo 0 >/sys/class/gpio/gpio${GPIO}/value
                sleep 0.01
        done
}

while true; do
        feed_dog
        sleep 10
done

